using UnityEngine;
using PopstrikeVR.Data;

namespace PopstrikeVR.Core
{
    /// <summary>
    /// Loads the JSON calibration data generated by the standalone calibration phase 
    /// (using the shared SaveManager) and injects it directly into the PatientProfileSO.
    /// </summary>
    public class PopstrikeProfileLoader : MonoBehaviour
    {
        [Tooltip("The Scriptable Object used by all Popstrike balloons and mappers.")]
        public PatientProfileSO TargetProfile;

        [Tooltip("Check this to use the Left Arm's ROM data. Uncheck for Right Arm.")]
        public bool UseLeftArm = true;

        private void Awake()
        {
            LoadCalibrationData();
        }

        public void LoadCalibrationData()
        {
            if (TargetProfile == null)
            {
                Debug.LogError("[PopstrikeProfileLoader] Target PatientProfileSO is missing!");
                return;
            }

            // Call the global SaveManager to read the guaranteed JSON file
            PlayerProfile savedProfile = SaveManager.LoadPlayerProfile();

            if (savedProfile == null || savedProfile.calibrationData == null)
            {
                Debug.LogError("[PopstrikeProfileLoader] Failed to load JSON profile from SaveManager!");
                return;
            }

            // Extract the correct arm data
            ArmData activeArm = UseLeftArm 
                ? savedProfile.calibrationData.leftArmData 
                : savedProfile.calibrationData.rightArmData;

            // 1. Inject Max Reach (ROM)
            if (activeArm.reachMax > 0.1f) 
            {
                TargetProfile.ReachRadius = activeArm.reachMax;
                Debug.Log($"[PopstrikeProfileLoader] Injected Reach Radius: {TargetProfile.ReachRadius}m from JSON.");
            }

            // 2. Inject Joint Angular Limits (Elevation / Azimuth)
            // shoulderFlexionMax determines how high they can safely lift their arm (Elevation)
            if (activeArm.shoulderFlexionMax > 1f)
            {
                TargetProfile.MaxElevation = activeArm.shoulderFlexionMax;
                Debug.Log($"[PopstrikeProfileLoader] Injected Max Elevation (Flexion): {TargetProfile.MaxElevation} degrees.");
            }
            
            // Note: We leave MinElevation at the ScriptableObject's safe default (-30 etc.) 
            // since ArmData does not currently store shoulderExtensionMax (downward reach).

            // --- ASYMMETRIC AZIMUTH MAPPING ---
            // Abduction is outward reach (away from body). Horizontal Adduction is inward reach (cross body).
            // We assume shoulderHorizontalAdductionMax.x is the inward limit (cross chest).
            
            float outwardLimit = activeArm.shoulderAbductionMax;
            float inwardLimit = activeArm.shoulderHorizontalAdductionMax.x; 

            if (outwardLimit > 1f || inwardLimit > 1f)
            {
                if (!UseLeftArm) // Right Arm
                {
                    // Right side is positive. Outward is positive, inward is negative.
                    if (outwardLimit > 1f) TargetProfile.MaxAzimuth = outwardLimit;
                    if (inwardLimit > 1f) TargetProfile.MinAzimuth = -inwardLimit; // Flip inward reach to negative azimuth
                }
                else // Left Arm
                {
                    // Left side is negative. Outward is negative, inward is positive.
                    if (outwardLimit > 1f) TargetProfile.MinAzimuth = -outwardLimit; // Flip outward reach to negative azimuth
                    if (inwardLimit > 1f) TargetProfile.MaxAzimuth = inwardLimit;
                }
                
                Debug.Log($"[PopstrikeProfileLoader] Injected Asymmetric Azimuth -> Min: {TargetProfile.MinAzimuth}, Max: {TargetProfile.MaxAzimuth}");
            }

            // 3. Inject Reaction Time -> Punch Velocity
            if (activeArm.reactionTime > 0.1f)
            {
                TargetProfile.MinimumPunchVelocity = 1.5f / activeArm.reactionTime;
                Debug.Log($"[PopstrikeProfileLoader] Injected Minimum Punch Velocity: {TargetProfile.MinimumPunchVelocity} m/s based on JSON Reaction Time.");
            }
        }
    }
}
